### ISSUE TITLE
TDH MOD_CH101 distance measurement Arduino Uno/ESP8266/ESP32 Code

### ISSUE THREAD

**Issue by amalkd** [sparkfunX/Qwiic_Chirp_101_Ultrasonic_Rangefinder#1]
I have TDK ultrasonic module MOD_CH101-03-02 and want to use it to measure the multiple objects distances using Arduino Uno/ESP32/ESP8266.

Please provide us the simple code which helps to interface the sensor with the microcontroller.

**Comment by nseidle** [comment]
Hi - There is not yet an Arduino compatible library for this sensor, however there is an API and extensive documentation available from TDK.

**Comment by jezdez** [comment]
> Hi - There is not yet an Arduino compatible library for this sensor, however there is an API and extensive documentation available from TDK.

@nseidle Hi there, could you pleas elaborate what you mean with "there is not yet an Arduino compatible library for this sensor"?

E.g. are you saying that SparkFun is working on one and it just hasn't been released yet but it's coming? Or is it a matter of the community to write (based on TDK's docs) and release one?

I'm asking since a lot of people in various forums have struggled getting this board (and chip) to run in even the most simple applications, I've yet to see one being shared publicly. And since you're still [selling the Qwiic board](https://www.sparkfun.com/products/17046), I was trying to understand what I can expect. Same is true for the relatively [new SMT version of it](https://www.sparkfun.com/products/17271), right?

Your clarification would definitely help, thank you!

**Comment by nseidle** [comment]
Howdy! SparkFun is not currently working on a library nor do we currently plan to for the MOD-CH101 or the SMD version of the CH101. I welcome any collaboration or PR! We have so many other fun projects currently at play; it would be some time before the CH101 got high enough on the list for us to tackle an Arduino wrapper for TDK's API.

**Comment by jezdez** [comment]
> Howdy! SparkFun is not currently working on a library nor do we currently plan to for the MOD-CH101 or the SMD version of the CH101. I welcome any collaboration or PR! We have so many other fun projects currently at play; it would be some time before the CH101 got high enough on the list for us to tackle an Arduino wrapper for TDK's API.

Awesome, thank you for the clarification, totally understood! 🙌🏻
